fix task1
BodyanB/altexsoft-lab-2020 pull request #1
Opened 2020-08-04 10:57 UTC by BodyanB

Please view the code

2020-08-04 12:41 UTC, alex-geraschenko requested changes
Постарайтесь разнести методы задач по разным классам в соответствии с принципами SOLID

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            string path = @"C:\Users\User\source\repos\altexsoft-lab-2020\ConsoleApp\ConsoleApp\bin\Debug\work.txt";
А что будет, если путь поменяется ?

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            string pathNew = @"C:\Users\User\source\repos\altexsoft-lab-2020\ConsoleApp\ConsoleApp\bin\Debug\note.txt";
А что будет, если путь поменяется ?

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +                    var charsToRemove = new string[] { "@", ",", ".", ";", "'", "!", "?", "(", ")" };
Обратите внимание на регулярные выражения

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            if (Regex.Matches(readText, pattern).Count == 0)
Проверку лучше делать до преобразований

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            string[] words = readText.Split(new char[] { ' ', '"', '.', '?', '!', ',', '(', ')' }, StringSplitOptions.RemoveEmptyEntries);
Обратите внимание на регулярные выражения

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            string readText = File.ReadAllText(path);
Нет проверки на существование файла

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            using (StreamReader str = File.OpenText(path))
Нет проверки на существование файла

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +            using (StreamReader fs = File.OpenText(path))
Нет проверки на существование файла

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +                {
Логику можно упростить

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +                for (int i = 0; i < dirs.Length; i++)
Нет сортировки

2020-08-04 12:41 UTC, alex-geraschenko commented on ConsoleApp/Program.cs
> +                foreach (string fl in fls)
Нет сортировки

2020-08-12 16:26 UTC, alex-geraschenko requested changes

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +        private List<string> m_datafromfile = new List<string>();
В C# приватные поля принято называть начиная с `_` без префикса `m`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +        public List<string> MAINMENUFILEDATA
В C# публичные свойства принято называться в `PascalCase`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +        public string[] FILEPATHS
В C# публичные свойства принято называться в `PascalCase`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +            get
Используйте `Auto Property`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +            get
Используйте `Auto Property`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +        private void readRelaventFile()
В C# все методы принято называть в `PascalCase`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +        public void showMenuScreen()
В C# все методы принято называть в `PascalCase`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +        top: foreach (string item in MAINMENUFILEDATA)
Использование меток и `goto` плохая практика. Постарайтесь найти другое решение

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +            StreamReader srObj = new StreamReader(path);
Изучите, что такое `IDisposable`, `Dispose` и конструкция `using`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/Menu.cs
> +        public void readFilesPath()
В C# все методы принято называть в `PascalCase`

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/ReadPath.cs
> +    internal class ReadFile
Классы принято называть в существительными

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/ReadText.cs
> +    class ReadText : ReadFile
Классы принято называть в существительными

2020-08-12 16:26 UTC, alex-geraschenko commented on ConsoleApp/CountWord.cs
> +    class CountWord : ReadText
Классы принято называть в существительными

2020-08-18 20:09 UTC, serhii-shkodenko requested changes

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/FolderName.cs
> +                Console.WriteLine("The process failed: {0}", e.ToString());
Вы вызываете ToString() на объекте, а Вам нужен текст исключения.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/FolderName.cs
> +                Console.WriteLine("The process failed: {0}", e.ToString());
Вы вызываете ToString() на объекте, а Вам нужен текст исключения.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Menu.cs
> +        static public string Comand;
В C# принято указываеть модификаторы доступа в самом начале, перед всеми остальными модификаторами. 
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017
csharp_preferred_modifier_order = public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async:silent

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Menu.cs
> +            string autndate = "Author: B/B\t\t\t\t\t  Date:" + System.DateTime.Now;
Локальные переменные следует именовать в `camelCase`.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Menu.cs
> +                Console.WriteLine("1. Считать по указанному в пути текстовый файл и удалить в нем указанный в консоли символ/слово.");
Вот так выглядит у меня меню на моей машине с английской локалью: 
![encoding_error](https://user-images.githubusercontent.com/69808191/90545620-9389a380-e191-11ea-8377-6649e3a1117d.png)

Пожалуйста, установите необходимую кодировку для консоли.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Menu.cs
> +                Console.WriteLine(autndate);
Задумайтесь, что будет если пользователь не введет ни один из перечисленных Вами вариантов. Например, будет повторяться одно и то же время.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Menu.cs
> +        static public string Comand;
Вы используете переменную `Comand` только внтури метода. Раз она Вам нужна только там, то и опеределяйте ее там.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/FolderName.cs
> +            Dictionary<Int32, string> dirеctory = new Dictionary<int, string>();
Следует использовать сокращеннное наименование типа.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/FolderName.cs
> +        public void FName()
В С# следует использовать глаголы для имен методов
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Path.cs
> +    internal class ReadFile
В своем коде Вы наследуетесь от этого класса. Если абстрагироваться от текущей реализации, очевидно, этот класс предназначен для инкапсуляции логики чтения файла. Вполне вероятно, что Вам понадобится использовать этот механизм в разных частях Вашей программы. Поэтому кажется неразумным "запирать" его в рамках одной библиотеки.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Text.cs
> +            if (String.IsNullOrEmpty(word))
Следует использовать более простое наименование типа.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Path.cs
> +    internal class ReadFile
Имя файла принято называть так же, как и имя класса

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Text.cs
> +                    Console.Write("Введите путь для сохранения файла: ");
Вы выделили логику чтения файла в отдельный класс, почему не поступили так же с логикой записи?

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Text.cs
> +                    string writePathFile = writePath + "note.txt";
Я бы вынес название файла в константу.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/ThirdSentence.cs
> +        public void TSentence()
Название метода должно быть в глагольной форме
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/ThirdSentence.cs
> +                Console.WriteLine(String.Join(' ', reverseWords));
Просто `string`

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Word.cs
> +        public void CWord()
Приведите название метода в глагольную форму. 
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Word.cs
> +            string[] words = textStream.Split(new char[] { ' ', '"', '.', '?', '!', ',', '(', ')' }, StringSplitOptions.RemoveEmptyEntries);
Используйте регулярные выражения.

2020-08-18 20:09 UTC, serhii-shkodenko commented on ConsoleApp/Word.cs
> +            Console.WriteLine(String.Join(',', resultWords));
Упростите используемое имя типа.

2020-08-19 07:11 UTC, BodyanB commented
Доброе утро Сергей. Я так понимаю что теперь с Вами работаю?

вт, 18 авг. 2020 г. в 23:09, Sergiy <notifications@github.com>:

> *@serhii-shkodenko* requested changes on this pull request.
> ------------------------------
>
> In ConsoleApp/FolderName.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472348424>
> :
>
> > +            Dictionary<Int32, string> dirеctory = new Dictionary<int, string>();
> +            try
> +            {
> +                string[] dirs = Directory.GetDirectories(path, "*", SearchOption.TopDirectoryOnly);
> +                Array.Sort(dirs);
> +                Console.WriteLine("The number of directories is {0}.", dirs.Length);
> +                for (int i = 0; i < dirs.Length; i++)
> +                {
> +                    dirеctory.Add(i + 1, dirs[i]);
> +                    Console.WriteLine($" {i + 1}.{dirs[i]}");
> +                }
> +
> +            }
> +            catch (Exception e)
> +            {
> +                Console.WriteLine("The process failed: {0}", e.ToString());
>
> Вы вызываете ToString() на объекте, а Вам нужен текст исключения.
> ------------------------------
>
> In ConsoleApp/FolderName.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472348913>
> :
>
> > +
> +
> +            try
> +            {
> +
> +                string[] fls = Directory.GetFiles(targetDirectory, "*");
> +                Array.Sort(fls);
> +                Console.WriteLine("The number of files is {0}.", fls.Length);
> +                foreach (string fl in fls)
> +                {
> +                    Console.WriteLine(fl);
> +                }
> +            }
> +            catch (Exception e)
> +            {
> +                Console.WriteLine("The process failed: {0}", e.ToString());
>
> Вы вызываете ToString() на объекте, а Вам нужен текст исключения.
> ------------------------------
>
> In ConsoleApp/Menu.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472356093>
> :
>
> > @@ -0,0 +1,70 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.Text;
> +using System.Linq;
> +using System.Threading.Tasks;
> +using System.IO;
> +using System.Threading;
> +
> +namespace ConsoleApp
> +{
> +    class Menu
> +    {
> +        static public string Comand;
>
> В C# принято указываеть модификаторы доступа в самом начале, перед всеми
> остальными модификаторами.
>
> https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017
> csharp_preferred_modifier_order =
> public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async:silent
> ------------------------------
>
> In ConsoleApp/Menu.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472358896>
> :
>
> > +using System.Collections.Generic;
> +using System.Text;
> +using System.Linq;
> +using System.Threading.Tasks;
> +using System.IO;
> +using System.Threading;
> +
> +namespace ConsoleApp
> +{
> +    class Menu
> +    {
> +        static public string Comand;
> +
> +        public void ShowMenuScreen()
> +        {
> +            string autndate = "Author: B/B\t\t\t\t\t  Date:" + System.DateTime.Now;
>
> Локальные переменные следует именовать в camelCase.
> ------------------------------
>
> In ConsoleApp/Menu.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472364588>
> :
>
> > +{
> +    class Menu
> +    {
> +        static public string Comand;
> +
> +        public void ShowMenuScreen()
> +        {
> +            string autndate = "Author: B/B\t\t\t\t\t  Date:" + System.DateTime.Now;
> +
> +            while (true)
> +            {
> +
> +                if (Comand == "5") break;
> +                Console.WriteLine(autndate);
> +                Console.WriteLine("### MENU ###");
> +                Console.WriteLine("1. Считать по указанному в пути текстовый файл и удалить в нем указанный в консоли символ/слово.");
>
> Вот так выглядит у меня меню на моей машине с английской локалью:
> [image: encoding_error]
> <https://user-images.githubusercontent.com/69808191/90545620-9389a380-e191-11ea-8377-6649e3a1117d.png>
>
> Пожалуйста, установите необходимую кодировку для консоли.
> ------------------------------
>
> In ConsoleApp/Menu.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472404270>
> :
>
> > +
> +namespace ConsoleApp
> +{
> +    class Menu
> +    {
> +        static public string Comand;
> +
> +        public void ShowMenuScreen()
> +        {
> +            string autndate = "Author: B/B\t\t\t\t\t  Date:" + System.DateTime.Now;
> +
> +            while (true)
> +            {
> +
> +                if (Comand == "5") break;
> +                Console.WriteLine(autndate);
>
> Задумайтесь, что будет если пользователь не введет ни один из
> перечисленных Вами вариантов. Например, будет повторяться одно и то же
> время.
> ------------------------------
>
> In ConsoleApp/Menu.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472407384>
> :
>
> > @@ -0,0 +1,70 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.Text;
> +using System.Linq;
> +using System.Threading.Tasks;
> +using System.IO;
> +using System.Threading;
> +
> +namespace ConsoleApp
> +{
> +    class Menu
> +    {
> +        static public string Comand;
>
> Вы используете переменную Comand только внтури метода. Раз она Вам нужна
> только там, то и опеределяйте ее там.
> ------------------------------
>
> In ConsoleApp/FolderName.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472421681>
> :
>
> > @@ -0,0 +1,54 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.IO;
> +using System.Text;
> +
> +namespace ConsoleApp
> +{
> +    class FolderName
> +    {
> +        public void FName()
> +        {
> +            Console.WriteLine(@"Enter the path:");
> +            string path = Console.ReadLine();
> +            Dictionary<Int32, string> dirеctory = new Dictionary<int, string>();
>
> Следует использовать сокращеннное наименование типа.
> ------------------------------
>
> In ConsoleApp/FolderName.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472422619>
> :
>
> > @@ -0,0 +1,54 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.IO;
> +using System.Text;
> +
> +namespace ConsoleApp
> +{
> +    class FolderName
> +    {
> +        public void FName()
>
> В С# следует использовать глаголы для имен методов
>
> https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-1.1/4df752aw(v=vs.71)
> ------------------------------
>
> In ConsoleApp/Path.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472428694>
> :
>
> > @@ -0,0 +1,25 @@
> +﻿using System;
> +using System.IO;
> +
> +namespace ConsoleApp
> +{
> +    internal class ReadFile
>
> В своем коде Вы наследуетесь от этого класса. Если абстрагироваться от
> текущей реализации, очевидно, этот класс предназначен для инкапсуляции
> логики чтения файла. Вполне вероятно, что Вам понадобится использовать этот
> механизм в разных частях Вашей программы. Поэтому кажется неразумным
> "запирать" его в рамках одной библиотеки.
> ------------------------------
>
> In ConsoleApp/Text.cs
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#discussion_r472432795>
> :
>
> > +using System.Text;
> +using System.IO;
> +using System.Linq;
> +using System.Text.RegularExpressions;
> +
> +namespace ConsoleApp
> +{
> +    class Text : ReadFile
> +    {
> +
> +        public void RText()
> +        {
> +            string textStream = ReadT();
> +            Console.Write("Введите слово или символ для удаления. ");
> +            string word = Console.ReadLine();
> +            if (String.IsNullOrEmpty(word))
>
> Следует использовать более простое наименование типа.
> ------------------------------
>
> In ConsoleApp/Path.cs
> <https://github.com/BodyanB/altexsoft-lab [...]

2020-08-19 08:26 UTC, serhii-shkodenko commented
> Доброе утро Сергей. Я так понимаю что теперь с Вами работаю?

Вы работаете со всеми менторами. Всех участников курсов будут ревьююить либо кто-то из нас, либа оба ментора.

2020-08-20 09:23 UTC, alex-geraschenko commented
У Вас еще не все комментарии исправлены, поэтому делать ревью еще рано

2020-08-20 10:18 UTC, BodyanB commented
Добрый день. Какие комментарии исправить?

чт, 20 авг. 2020 г. в 12:23, Alex Geraschenko <notifications@github.com>:

> У Вас еще не все комментарии исправлены, поэтому делать ревью еще рано
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#issuecomment-677485345>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDOC6PDGEF44UZMERPDSBTTSVANCNFSM4PUIWR5A>
> .
>

2020-08-20 10:26 UTC, serhii-shkodenko commented
Те замечания, которые Вы исправили в своем последнем коммите, пожалуйста, пометьте исправленными через кнопку Resolve Conversation. Кроме того, последний Ваш коммит не содержит всех исправлений, насколько я успел его прсмотреть.

2020-08-20 11:18 UTC, BodyanB commented
Все замечания были исправлены.

чт, 20 авг. 2020 г. в 13:26, Sergiy <notifications@github.com>:

> Те замечания, которые Вы исправили в своем последнем коммите, пожалуйста,
> пометьте исправленными через кнопку Resolve Conversation. Кроме того,
> последний Ваш коммит не содержит всех исправлений, насколько я успел его
> прсмотреть.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#issuecomment-677514129>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDN6VK22VIMXROCGQBTSBT263ANCNFSM4PUIWR5A>
> .
>

2020-08-21 19:26 UTC, alex-geraschenko commented
Пересмотрите еще раз все замечания, которые есть на вкладке Conversation, и убедитесь, что все замечания поняты и исправлены.

2020-08-22 05:56 UTC, BodyanB commented
Хорошо.

On Fri, Aug 21, 2020, 22:26 Alex Geraschenko <notifications@github.com>
wrote:

> Пересмотрите еще раз все замечания, которые есть на вкладке Conversation,
> и убедитесь, что все замечания поняты и исправлены.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#issuecomment-678453860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDJ2FPE5CK45L3HHM7DSB3C7DANCNFSM4PUIWR5A>
> .
>

2020-08-22 19:13 UTC, BodyanB commented
Добрый вечер. Все комментарии исправлены, либо переписаны.

2020-08-25 19:05 UTC, alex-geraschenko commented
> Добрый вечер. Все комментарии исправлены, либо переписаны.

Вы уверены? А если зайти на вкладку **Files changed** и посмотреть там?

2020-08-25 21:29 UTC, BodyanB commented on ConsoleApp/Path.cs
> +    internal class ReadFile
В этом месте не понял что именно поправить, можно уточнить?

2020-08-26 12:25 UTC, BodyanB commented
Добрый день Александр. Те замечания что в  *Files changed* тоже поправил.

вт, 25 авг. 2020 г. в 22:05, Alex Geraschenko <notifications@github.com>:

> Добрый вечер. Все комментарии исправлены, либо переписаны.
>
> Вы уверены? А если зайти на вкладку *Files changed* и посмотреть там?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#issuecomment-680214869>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDLXJRBTADRO4GQSR5LSCQDPRANCNFSM4PUIWR5A>
> .
>

2020-08-26 16:44 UTC, alex-geraschenko approved these changes
Есть нюансы в именовании классов - из имени не понятно, для чего нужен класс. Для этого надо почитать Боба Мартина "Чистый Код".  Но в целом пойдет. Можно мержить и переходить ко второму заданию

2020-08-26 17:26 UTC, BodyanB commented
Спасибо.

ср, 26 авг. 2020 г. в 19:44, Alex Geraschenko <notifications@github.com>:

> *@alex-geraschenko* approved this pull request.
>
> Есть нюансы в именовании классов - из имени не понятно, для чего нужен
> класс. Для этого надо почитать Боба Мартина "Чистый Код". Но в целом
> пойдет. Можно мержить и переходить ко второму заданию
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BodyanB/altexsoft-lab-2020/pull/1#pullrequestreview-475672222>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUJLDOROYSDB45L423V573SCU3YRANCNFSM4PUIWR5A>
> .
>

2020-08-26 17:45 UTC, merged